version: "3"

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        ports:
            - "80:80"
        volumes:
            - .:/app
            - /app/node_modules

    test:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
        command: ["npm", "run", "test"]
